main: me.dewrs.GrantRank
name: GrantRank
author: dewrs
version: 2.1.1
api-version: 1.13
depend: [LuckPerms]

commands:
  grant:
    description: Grant a rank to a player
  grants:
    description: View actual player grants
  grantadmin:
    aliases: [gadmin, grantsadmin]
    description: Command for admins